name: "DEV PROD"

on: 
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs: 
  terraform:
    uses: ./.github/workflows/terraform.yml
    with: 
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::022499001444:role/github-actions-wagaodev-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "wagaodev-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "wagaodev-sa-east-1-terraform-lock"